// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB4XDup-HNMfWiMzuco0Piuptr03oTVIo4",
      authDomain: "reflectify-5043c.firebaseapp.com",
      projectId: "reflectify-5043c",
      storageBucket: "reflectify-5043c.firebasestorage.app",
      messagingSenderId: "819296103358",
      appId: "1:819296103358:web:7bb269dd8115634cbda7ef",
      measurementId: "G-X14LSFNC46");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFx4Kvb9ZwnJCjYltnEtqm4Py7iLT3kmI',
    appId: '1:819296103358:android:abeb55a4c8a064ffbda7ef',
    messagingSenderId: '819296103358',
    projectId: 'reflectify-5043c',
    storageBucket: 'reflectify-5043c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qGQmv10roIPRqwB1OQ3BOTiWZMeLecA',
    appId: '1:819296103358:ios:5c6378d1465f5f38bda7ef',
    messagingSenderId: '819296103358',
    projectId: 'reflectify-5043c',
    storageBucket: 'reflectify-5043c.firebasestorage.app',
    iosBundleId: 'com.example.healthApps',
  );
}
